### ISSUE TITLE
Lucas Pham - creating and organizing initial files

### ISSUE THREAD

**Issue by a-sane-human-being** [CSAllenISD/2023-ISP-unIQue#17]

**Comment by MasonG31** [comment]
How will these files be shared as a group? It was been difficult early on in our project to have shared work, rather than just splitting it up among the people in our project group. When creating these files, would it be possible that we could access them at the same time and work on them together? I have done this in the past in the git project manager, but it was difficult to work on them at exactly the same time. I think it would be in our best interests to figure out a way for us to work on files at the same time. Thanks, Mason.

**Comment by Delikatessen** [comment]
We've got the main directories setup and each department has their own development branch! I think we're pretty good at this, y'all.
