### ISSUE TITLE
Learn JavaScript

### ISSUE THREAD

**Issue by SophieH8** [CSAllenISD/2023-ISP-unIQue#25]
Learn Java script for the games

**Comment by FarazPir** [comment]
This is really important because the games are an important part of our idea and we need to learn JavaScript to proceed with it. We should not hold off on this for too long.

**Comment by MasonG31** [comment]
That's great point, we should start learning now so we have a sound foundation for when we begin coding.

**Comment by SterbenShell** [comment]
Since Java Script is the language we are using for the games this will be an important step for everyone moving forward. We should try to get this out of the way as efficiently as possible to maximize our time working on the project.

**Comment by Mehak-J** [comment]
Yes, we'll definitely need to know JavaScript for the key design features within the game.

**Comment by Delikatessen** [comment]
we should start experimenting with javascript asap, and not wait to start until we desperately need to use it. I'm gonna link a javascript compiler we can use to help us grasp the fundamentals.

[compiler](https://playcode.io/javascript-online)

**Comment by MasonG31** [comment]
One potential alternative point to this issue would be that we learn javascript along the way of coding our website. I don't know if it would fully necessary to learn the entire language along the way for this one feature. For example, it's like taking a Spanish course so we can sing a song in Spanish. Wouldn't it make more sense to just learn the song, in our case, to just learn how to code a website in javascript, rather than take notes and watch javascript videos? What do y'all think? Mason Graham

**Comment by FarazPir** [comment]
@MasonG31 I believe that what you suggested is basically what we are planning on doing. Currently how I'm doing it is I started with learning the basics, then from there I only look up things that help me with what I'm working on. I agree that trying to learn the entire language at once is not a good idea.

**Comment by MasonG31** [comment]
That sounds great Faraz, I purchased a Javascript book last month and am slowly working through it. I agree with you, that sounds like it will work great!

**Comment by Delikatessen** [comment]
This issue will never be "Completed", clearing for the sake of organization.
