### ISSUE TITLE
JavaScript Coding location

### ISSUE THREAD

**Issue by SterbenShell** [CSAllenISD/2023-ISP-unIQue#33]
Find a place where we can code our project using javascript

**Comment by MasonG31** [comment]
I think goes hand in hand with finding the HTML website where we code in Javascript for our website. From the research I have been doing, we can code the website in HTML like we have been doing for our journals. But, inside of the HTML we can embed javascript, and we can code our games with the javascript.  Because we are more familiar with HTML, it would make sense to code as much as we can in HTML, before switching to javascript.

**Comment by Delikatessen** [comment]
Google searches work wonders yall. Use https://liveweave.com/ , liveweave is realtime CSS, HTML, and Javascript.

**Comment by FarazPir** [comment]
Most javascript code will be in index.js. More .js files will be made if necessary.
